name: 01 - Building Blocks
on: 
  - push
  
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello hi
        run: echo "hello world"
  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: failed job
        run: |
          echo "its  not failed job"
          
    
      - name: echo naming bye
        run : echo "byes byes"
      

       
