name: 01 - Building Blocks
on: 
  - workflow_dispatch
  - push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello hi
        run: echo "hello world"
  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: echo naming bye
        run : echo "byes byes"
      

       
