name: sample-action
on: workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello hi
        run: echo "hello world"
  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: echo naming bye
        run : echo "byes byes"
      

       
