name: using-actions
on: workflow_dispatch
jobs:
    using-actions:
        runs-on: ubuntu-latest
        steps:
           - name: checkout code
             uses: actions/checkout@v4
           - name: setup the node
             uses: actions/setup-node@v4
             with:
                node-version: '20.x'
           - name: install dependencies
             run: npm ci
             working-directory: react-app


