name: 05-01-filters and activity types
on:
    pull_request:
        types:
            - opened
            - synchronize 
        branches:
            - main
jobs:
    activity-types:
        runs-on: ubuntu-latest
        steps:
            - run: echo " Running when PR is opened or synchronised"
