name: 05-02-filters and activity types
on:
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
    activity-types:
        runs-on: ubuntu-latest
        steps:
            - run: echo " Running when PR is closed"
