name: 06-context 
run-name: 06- context | debug ${{inputs.debug}}
on: 
     
     workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: "MY WORKFLOW"
    OVERWRITTEN_VAR: "OVERWRITEN_WORKFLOW" 
jobs:
    context:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'JOB VARIABLE'
            OVERWRITTEN_VAR: 'JOB OVERWRITTEN'
        steps:
            - name: Display Information
              run: |
                echo "Event Name ${{github.event_name}} "
                echo "Reference ${{github.ref}} "
                echo "SHA ${{github.sha}} "
                echo "Actor ${{github.actor}} "
                echo "Workflow ${{github.workflow}} "
                echo "Run id ${{github.run_id}} "
                echo "Runner Number ${{github.run_number}} "
            - name: Retrive Variable
              run: |
                echo "Variable values: ${{vars.MY_VAR}}"
            - name: workflow variable
              env:
                OVERWRITTEN_VAR: 'STEPS_VAR'
              run: |
                echo " workflow variable: ${{env.OVERWRITTEN_VAR}}"
            - name: workflow variable
              run: |
                echo " workflow variable: ${{env.MY_WORKFLOW_VAR}}"
                echo " workflow variable: ${{env.OVERWRITTEN_VAR}}"
    Second-job:
        runs-on: ubuntu-latest
        steps:
            - name: workflow variable
              run: |
                echo " workflow variable: $MY_WORKFLOW_VAR "
                echo " workflow variable: $OVERWRITTEN_VAR "
  
          