name: 07-Expressions
run-name: 07-expression - if condition - ${{inputs.express && 'hari' || 'Aruna' }}
on:

  workflow_dispatch:
    inputs:
      express:
           type: boolean
           default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[express] pass Startup'
        if: ${{inputs.express}}
        run: |
            echo "Event Name ${{github.event_name}} "
            echo "Reference ${{github.ref}} "
            echo "SHA ${{github.sha}} "
            echo "Actor ${{github.actor}} "
            echo "Workflow ${{github.workflow}} "
            echo "Run id ${{github.run_id}} "
            echo "Runner Number ${{github.run_number}} "
      - name: '[express] fail Startup'
        if: ${{!inputs.express}}
        run: |
            echo "Event Name ${{github.event_name}} "
            echo "Reference ${{github.ref}} "
