name: 08-functions
on: 
    push:
    workflow_dispatch:
jobs:
    functions-usage:
        runs-on: ubuntu-latest
        steps:
            - name: i will execute when sucess
              if: ${{success()}}
              run: echo "sucess"
            - name: i will execute when failed
              if: ${{failure()}}
              run: echo "failure"
            - name: i will execute when cancelled
              if: ${{cancelled()}}
              run: echo "cancelled"
            - name: i will execute when sucess
              if: ${{!cancelled()}}
              run: echo "not cancelled"
            - name: i will execute when always
              if: ${{always()}}
              run: echo "always"
             