name: 11-outputs 
on:
    workflow_dispatch:
        inputs:
            result:
                type: choice
                options:
                    - success
                    - failure
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
           build-status: ${{steps.build.outputs.status}}
        steps:
            - name: print the output
              run: echo "$GITHUB_OUTPUT"
            - name: print the output
              id: build
              run: echo "status= ${{inputs.result}}" >>"$GITHUB_OUTPUT" 
    deploy-the-file:
        runs-on: ubuntu-latest
        needs: build
        if: ${{'failure' == 'failure'}}
        steps:
           - name: deploy
             run: echo "deploying"