name: 12-composite-custom-action
on:
    workflow_dispatch:
env:
    working-directory: 1-custom-action/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - uses: actions/checkout@v4
            - name: setup node and npm dependency
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 20.x
                working-dir: ${{env.working-directory}}
            - name: test
              run: npm run test
            - name: Build
              run: npm run build
